[workspace]
members = [
    "core",
    "program",
    "sdk", "shank-cli",
]
resolver = "2"

[workspace.package]
version = "0.0.1"
edition = "2021"
readme = "README.md"

[workspace.dependencies]
anyhow = "1.0.98"
envfile = "0.2.1"
jito-tip-payment-core = { path = "./core", version = "=0.0.1" }
jito-tip-payment-sdk = { path = "./sdk", version = "=0.0.1" }
litesvm = "0.6.1"
pinocchio = { version = "0.8.4" }
pinocchio-pubkey = "0.2.3"
pinocchio-system = "0.2.3"
shank = { version = "0.4.3-alpha.1", features = ["pinocchio"] }
solana-keypair = "2.2.0"
solana-instruction = "2.2.0"
solana-pubkey = "2.2.0"
solana-sdk-ids = "2.2.0"
solana-signer = "2.2.0"
solana-system-interface = "1.0"
solana-transaction = "2.2.0"
test-log = "0.2.17"
thiserror = "2.0.12"
env_logger = "0.11.8"
log = "0.4.27"
shank_idl = "0.4.3"
