[workspace]
members = [
    "program", "sdk",
]
resolver = "2"

[workspace.package]
version = "0.0.1"
edition = "2021"
readme = "README.md"

[workspace.dependencies]
jito-tip-payment-sdk = { path = "./sdk" }
pinocchio = { version = "0.8.4" }
pinocchio-system = "0.2.3"
thiserror = "2.0.12"
