[workspace]
members = [
    "api",
    "clients/rust/restaking_client",
    "clients/rust/vault_client",
]

resolver = "2"

[workspace.package]
version = "0.0.3"
edition = "2021"
readme = "README.md"

[workspace.dependencies]
anchor-lang = { version = "0.30.1", features = ["idl-build"] }
axum = "0.6.2"
borsh = { version = "0.10.3" }
bytemuck = { version = "1.16.3", features = ["min_const_generics"] }
clap = { version = "4.5.16", features = ["derive", "env"] }
http = "0.2.1"
jito-bytemuck = { git = "https://github.com/jito-foundation/restaking.git", rev = "eaf88e7e5ca2845fe3108c4fc4a06a25f9a8514d" }
jito-vault-client = { path = "clients/rust/vault_client", version = "=0.0.3" }
jito-vault-core = { path = "./core", version = "=0.0.3" }
num-derive = "0.4.2"
num-traits = "0.2.19"
reqwest = "0.11.27"
serde = { version = "^1.0", features = ["derive"] }
serde_with = "3.9.0"
serde_json = "1.0.102"
solana-account-decoder = { package = "solana-account-decoder", git = "https://github.com/jito-foundation/jito-solana.git", rev = "0bbcbe476c0e728907ac01135115e661c16538e5" }
solana-rpc-client = "~1.18"
solana-rpc-client-api = "~1.18"
solana-program = "~1.18"
solana-sdk = "~1.18"
thiserror = "1.0.57"
tokio = { version = "1.36.0", features = ["full"] }
tower = { version = "0.4.13", features = ["limit", "buffer", "timeout", "load-shed"] }
tower-http = { version = "0.4.0", features = ["trace"] }
tracing = { version = "0.1.37" }
tracing-core = "0.1.32"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
