[package]
name = "shank-cli"
version = "0.0.1"
edition = { workspace = true }

[dependencies]
anyhow = { workspace = true }
env_logger = { workspace = true }
envfile = { workspace = true }
log = { workspace = true }
shank_idl = { workspace = true }
