[package]
name = "jito-tip-payment-program"
version = "0.0.1"
edition = { workspace = true }

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
jito-tip-payment-sdk = { workspace = true }
pinocchio = { workspace = true }
pinocchio-system = { workspace = true }
