[package]
name = "vote-state"
version = { workspace = true }
edition = { workspace = true }
readme = { workspace = true }

[dependencies]
jito-tip-core = { workspace = true }
pinocchio = { workspace = true }
solana-program = { workspace = true }

[lints]
workspace = true
