name: ci

on:
  push:
    branches: [ master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  security_audit:
    name: security_audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install cargo-audit from crates.io
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-audit
          version: "0.21.1"
      - run: cargo audit --ignore RUSTSEC-2022-0093 --ignore RUSTSEC-2024-0344 --ignore RUSTSEC-2024-0421 --ignore RUSTSEC-2025-0022

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libudev-dev
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt, clippy
          toolchain: 1.84.1
      - name: Install cargo-sort from crates.io
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-sort
          version: "1.0.9"
      - run: cargo sort --workspace --check
      - run: cargo fmt --all --check
      - run: cargo clippy --all-features -- -D warnings -D clippy::all -D clippy::nursery -D clippy::integer_division -D clippy::arithmetic_side_effects -D clippy::style -D clippy::perf

  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libudev-dev
      - uses: aarcangeli/load-dotenv@v1.0.0
        with:
          path: config
          filenames: program.env
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: install solana toolsuite
        run: sh -c "$(curl -sSfL https://release.anza.xyz/v2.2.14/install)"
      - name: add to path
        run: echo "/home/runner/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
      - name: Building programs
        run: cargo-build-sbf
        env:
          JITO_TIP_PAYMENT_PROGRAM_ID: T1pyyaTNZsKv2WcRAB8oVnk93mLJw2XzjtVYqCsaHqf

  verified_build:
    name: verified_build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libudev-dev
      - run: docker pull --platform linux/amd64 solanafoundation/solana-verifiable-build:2.2.14
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install solana-verify from crates.io
        uses: baptiste0928/cargo-install@v3
        with:
          crate: solana-verify

      - run: solana-verify build --library-name jito_tip_payment_program --base-image solanafoundation/solana-verifiable-build:2.2.14

      - name: Upload jito_tip_payment_program.so
        uses: actions/upload-artifact@v4
        with:
          name: jito_tip_payment_program.so
          path: target/deploy/jito_tip_payment_program.so

  test_sbf:
    name: cargo test
    runs-on: ubuntu-latest
    needs:
      - verified_build
    steps:
      - uses: actions/checkout@v4
      - uses: aarcangeli/load-dotenv@v1.0.0
        with:
          path: config
          filenames: program.env
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libudev-dev
      - name: Download jito tip payment program
        uses: actions/download-artifact@v4
        with:
          name: jito_tip_payment_program.so
          path: target/sbpf-solana-solana/release/
      - uses: taiki-e/install-action@v2
        with:
          tool: nextest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: cargo nextest run --all-features
        env:
          SBF_OUT_DIR: ${{ github.workspace }}/target/sbpf-solana-solana/release
